name: user_repository
description: Repo for getting/setting users
version: 0.0.1
author: Igor Ianishevskyi
homepage: prophet.ninja

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.15.5+3
