const NUMBER_OF_DAYS_TO_SHOW = 7;
//
const indexToDay = {
  0: "TODAY",
  1: "TOMORROW",
  2: "DAY AFTER TOMORROW",
};
const dayToIndex = {
  "TODAY": 0,
  "TOMORROW": 1,
  "DAY AFTER TOMORROW": 2,
};

//
const CALENDAR_HEIGHT = 80.0;
const CALENDAR_DATE_HEIGHT = 56.0;
const CALENDAR_DATE_PADDING = 14.0;
const CALENDAR_SELECTED_DATE_MARGIN = 4.0;
const CALENDAR_SELECTED_DATE_PADDING = 14.0;
//
const SPACE_BETWEEN_CALENDAR_PROPHECY = 1.0;
const SPACE_AFTER_PROPHECY = 8.0;
const SPACE_BEFORE_AMBIANCE = 32.0;
const SPACE_AFTER_AMBIANCE = 16.0;
const PROPHECY_PADDING_HORIZONTAL = 16.0;
//

