const NUMBER_OF_DAYS_TO_SHOW = 7;
const indexToDay = {
  0: "TODAY",
  1: "TOMORROW",
  2: "DAY AFTER TOMORROW",
};
const dayToIndex = {
  "TODAY": 0,
  "TOMORROW": 1,
  "DAY AFTER TOMORROW": 2,
};
const SPACE_BETWEEN_CALENDAR_PROPHECY = 1.0;
const SPACE_AFTER_PROPHECY = 16.0;
const SPACE_AFTER_AMBIANCE = 16.0;
