const NUMBER_OF_DAYS_TO_SHOW = 1098;
//
const indexToDay = {
  0: "TODAY",
  1: "TOMORROW",
  2: "DAY AFTER TOMORROW",
};
const dayToIndex = {
  "TODAY": 0,
  "TOMORROW": 1,
  "DAY AFTER TOMORROW": 2,
};

//
const CALENDAR_HEIGHT = 80.0;
const CALENDAR_DATE_HEIGHT = 56.0;
const CALENDAR_ORDINARY_DATE_PADDING = 22.0;
const CALENDAR_SELECTED_DATE_MARGIN = 8.0;
const CALENDAR_SELECTED_DATE_PADDING = 14.0;
const CALENDAR_NEW_MONTH_WIDTH = 54.0;
const CALENDAR_NEW_YEAR_WIDTH = 168.0;
const CALENDAR_SEPARATOR_RADIUS = 16.0;
//
const SPACE_BETWEEN_CALENDAR_POLLS = 1.0;
const SPACE_BETWEEN_POLLS_PROPHECY = 8.0;
const SPACE_BEFORE_AMBIANCE = 32.0;
const SPACE_AFTER_AMBIANCE = 32.0;
//
const PROPHECY_PADDING_HORIZONTAL = 16.0;
const SWITCH_POSITIVE_PLANET_AT_SUM = 42.0;

/// if all prophecies are enabled
const DEFAULT_POSITIVE_PROPHECY_BOUND = 7.0;
const DEFAULT_NEGATIVE_PROPHECY_BOUND = 4.4;

/// othervise
const TWEAKED_POSITIVE_PROPHECY_BOUND = 7.4;
const TWEAKED_NEGATIVE_PROPHECY_BOUND = 4.0;
//
