name: base
description: main module
author: bgoncharuck
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  json_annotation: 3.1.1
  meta: 
  storage_access: 
  bloc: 
  equatable: 
  to_string: 
  
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: 
  json_serializable: 3.5.1

flutter:
