name: prophecies_repository
description: Repo for getting/setting data within the app
version: 0.0.1
author: Igor Ianishevskyi
homepage: prophet.ninja

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.12.10+2
  rxdart: ^0.23.0
  firebase_core: ^0.4.0+8
  dataclass: ^0.3.0+1
  json_annotation: ^3.0.1
  firestore_annotations: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.9.0
  dataclass_generator: ^0.3.0+2
  json_serializable: ^3.2.5
  firestore_serializable: ^0.0.11
