import 'package:meta/meta.dart';
import 'package:base/prophecy/entity/prophecy.dart';
// private
import 'src/models.dart';

const SymbolCombinations = <PropheciesRange, SymbolCombination>{
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 9,
    mineral: Gem.BlueTourmaline,
    colors: [Color.White, Color.BlueGrey, Color.PurpleLight],
    tarrot: TarrotMajor.TheHermit,
    name: "sheep",
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Amethyst,
    colors: [Color.White, Color.Grey, Color.BlueGrey],
    tarrot: TarrotMajor.Rebirth,
    name: "skeleton",
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 9,
    mineral: Gem.Diamond,
    colors: [Color.Grey, Color.Green, Color.Pink],
    tarrot: TarrotMajor.TheTower,
    name: "atlas",
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Pearl,
    colors: [Color.Purple, Color.BlueLight, Color.RedDeep],
    tarrot: TarrotMajor.TheHighPriestess,
    name: "gamayun",
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 8,
    mineral: Gem.Peridot,
    colors: [Color.White, Color.Orange, Color.Blue],
    tarrot: TarrotMajor.TheFool,
    name: "small_monkey",
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 9,
    mineral: Gem.PurpleSpinel,
    colors: [Color.Pink, Color.RedLight, Color.White],
    tarrot: TarrotMajor.TheHermit,
    name: "lotus",
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Pearl,
    colors: [Color.Cyan, Color.BlueGrey, Color.Teal],
    tarrot: TarrotMajor.Lust,
    name: "meramid",
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Alexandrite,
    colors: [Color.Grey, Color.Yellow, Color.Purple],
    tarrot: TarrotMajor.TheMoon,
    name: "owl",
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.YellowSapphire,
    colors: [Color.BlueLight, Color.YellowLight, Color.White],
    tarrot: TarrotMajor.TheHighPriestess,
    name: "wisdom",
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 5,
    mineral: Gem.Emerald,
    colors: [Color.Green, Color.OrangeDeep, Color.OrangeLight],
    tarrot: TarrotMajor.TheFool,
    name: "leprechaun",
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.BlueTourmaline,
    colors: [Color.Blue, Color.Yellow, Color.Black],
    tarrot: TarrotMajor.TheHighPriestess,
    name: "butterfly",
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 9,
    mineral: Gem.BlueSapphire,
    colors: [Color.Grey, Color.Blue, Color.PurpleLight],
    tarrot: TarrotMajor.TheHighPriestess,
    name: "cards_deck",
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Garnet,
    colors: [Color.YellowLight, Color.OrangeLight, Color.GreenLight],
    tarrot: TarrotMajor.Temperance,
    name: "fairy",
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.BlueSapphire,
    colors: [Color.BlueLight, Color.Lime, Color.GreenDeep],
    tarrot: TarrotMajor.Justice,
    name: "turtle",
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Opal,
    colors: [Color.Lime, Color.Brown, Color.GreenLight],
    tarrot: TarrotMajor.TheEmpress,
    name: "snail",
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 7,
    mineral: Gem.Kyanite,
    colors: [Color.BlueDeep, Color.OrangeLight, Color.Green],
    tarrot: TarrotMajor.TheWheelOfFortune,
    name: "qilin",
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 6,
    mineral: Gem.Rhodolite,
    colors: [Color.YellowLight, Color.Brown, Color.Lime],
    tarrot: TarrotMajor.TheLovers,
    name: "seahorse",
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Citrine,
    colors: [Color.PurpleDeep, Color.OrangeLight, Color.YellowLight],
    tarrot: TarrotMajor.TheHighPriestess,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 6,
    mineral: Gem.Citrine,
    colors: [Color.Lime, Color.Brown, Color.BlueGrey],
    tarrot: TarrotMajor.TheStar,
    name: "dragon_turtle",
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Chrysolite,
    colors: [Color.Green, Color.Pink, Color.Lime],
    tarrot: TarrotMajor.TheEmpress,
    name: "clover",
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 5,
    mineral: Gem.BlackTopaz,
    colors: [Color.PinkDeep, Color.BlueDeep, Color.Purple],
    tarrot: TarrotMajor.TheFool,
    name: "joker",
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 7,
    mineral: Gem.FireOpal,
    colors: [Color.RedLight, Color.Orange, Color.Red],
    tarrot: TarrotMajor.TheHierophant,
    name: "fu_dog",
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 7,
    mineral: Gem.YellowSapphire,
    colors: [Color.Black, Color.White, Color.Yellow],
    tarrot: TarrotMajor.Lust,
    name: "lemur",
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 5,
    mineral: Gem.Pearl,
    colors: [Color.BlueDeep, Color.Brown, Color.RedDeep],
    tarrot: TarrotMajor.TheSun,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 6,
    mineral: Gem.Beryl,
    colors: [Color.PurpleLight, Color.BlueLight, Color.Lime],
    tarrot: TarrotMajor.TheLovers,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.BlueSapphire,
    colors: [Color.RedDeep, Color.White, Color.Brown],
    tarrot: TarrotMajor.Judgment,
    name: "centicore",
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Diamond,
    colors: [Color.Red, Color.Purple, Color.Pink],
    tarrot: TarrotMajor.Lust,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Ruby,
    colors: [Color.White, Color.Brown, Color.Grey],
    tarrot: TarrotMajor.TheLovers,
    name: "rabbit",
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 7,
    mineral: Gem.Peridot,
    colors: [Color.GreenDeep, Color.Red, Color.Lime],
    tarrot: TarrotMajor.TheStar,
    name: "frog",
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 9,
    mineral: Gem.Kyanite,
    colors: [Color.Teal, Color.White, Color.Cyan],
    tarrot: TarrotMajor.TheHangedMan,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 7,
    mineral: Gem.Beryl,
    colors: [Color.Teal, Color.Cyan, Color.BlueDeep],
    tarrot: TarrotMajor.TheMoon,
    name: "kappa",
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 8,
    mineral: Gem.Carbuncle,
    colors: [Color.BlueGrey, Color.Grey, Color.Teal],
    tarrot: TarrotMajor.TheTower,
    name: "elephant",
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Diamond,
    colors: [Color.BlueDeep, Color.OrangeLight, Color.RedLight],
    tarrot: TarrotMajor.TheMoon,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 8,
    mineral: Gem.RedSpinel,
    colors: [Color.PurpleDeep, Color.RedDeep, Color.White],
    tarrot: TarrotMajor.TheEmperor,
    name: "crown",
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 7,
    mineral: Gem.Citrine,
    colors: [Color.Yellow, Color.OrangeLight, Color.White],
    tarrot: TarrotMajor.Judgment,
    name: "yellow_dragon",
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Garnet,
    colors: [Color.PinkDeep, Color.GreenLight, Color.PurpleLight],
    tarrot: TarrotMajor.TheHierophant,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.BlueSapphire,
    colors: [Color.RedDeep, Color.BlueDeep, Color.BlueGrey],
    tarrot: TarrotMajor.TheChariot,
    name: "crab",
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.OrangeTopaz,
    colors: [Color.Grey, Color.Brown, Color.PinkDeep],
    tarrot: TarrotMajor.TheHangedMan,
    name: "mouse",
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Zircon,
    colors: [Color.Green, Color.Red, Color.Yellow],
    tarrot: TarrotMajor.TheWheelOfFortune,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Rhodolite,
    colors: [Color.Purple, Color.Teal, Color.Grey],
    tarrot: TarrotMajor.TheWorld,
    name: "spider",
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 6,
    mineral: Gem.Garnet,
    colors: [Color.White, Color.RedLight, Color.YellowLight],
    tarrot: TarrotMajor.TheChariot,
    name: "orchids",
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.FireOpal,
    colors: [Color.Lime, Color.Blue, Color.Pink],
    tarrot: TarrotMajor.TheEmpress,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.OrangeTopaz,
    colors: [Color.RedDeep, Color.PurpleDeep, Color.GreenLight],
    tarrot: TarrotMajor.Temperance,
    name: "horse",
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 6,
    mineral: Gem.Aquamarine,
    colors: [Color.BlueLight, Color.Blue, Color.BlueDeep],
    tarrot: TarrotMajor.TheMagician,
    name: "dolphin",
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 7,
    mineral: Gem.BlueTourmaline,
    colors: [Color.BlueLight, Color.BlueGrey, Color.Grey],
    tarrot: TarrotMajor.TheStar,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 5,
    mineral: Gem.Emerald,
    colors: [Color.PinkLight, Color.Green, Color.Yellow],
    tarrot: TarrotMajor.TheFool,
    name: "caravan_trader",
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Pearl,
    colors: [Color.BlueDeep, Color.Red, Color.White],
    tarrot: TarrotMajor.TheFool,
    name: "compass",
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.OrangeTopaz,
    colors: [Color.Orange, Color.OrangeLight, Color.Lime],
    tarrot: TarrotMajor.Temperance,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Pearl,
    colors: [Color.Yellow, Color.BlueLight, Color.Lime],
    tarrot: TarrotMajor.TheMoon,
    name: "household_deity",
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 5,
    mineral: Gem.Beryl,
    colors: [Color.Black, Color.Cyan, Color.OrangeDeep],
    tarrot: TarrotMajor.Strength,
    name: "black_cat",
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 6,
    mineral: Gem.Amethyst,
    colors: [Color.PinkDeep, Color.PurpleLight, Color.Purple],
    tarrot: TarrotMajor.TheLovers,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 7,
    mineral: Gem.Zircon,
    colors: [Color.Lime, Color.YellowLight, Color.Orange],
    tarrot: TarrotMajor.TheMagician,
    name: "green_dragon",
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.PurpleSpinel,
    colors: [Color.OrangeDeep, Color.PurpleLight, Color.Orange],
    tarrot: TarrotMajor.Temperance,
    name: "squirrel",
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.RedSpinel,
    colors: [Color.OrangeDeep, Color.RedDeep, Color.PurpleDeep],
    tarrot: TarrotMajor.TheChariot,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 5,
    mineral: Gem.Alexandrite,
    colors: [Color.Yellow, Color.Grey, Color.Brown],
    tarrot: TarrotMajor.Temperance,
    name: "boar",
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Kyanite,
    colors: [Color.Red, Color.GreenDeep, Color.BlueGrey],
    tarrot: TarrotMajor.TheEmperor,
    name: "crocodile",
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 8,
    mineral: Gem.Amber,
    colors: [Color.Black, Color.BlueDeep, Color.Yellow],
    tarrot: TarrotMajor.Justice,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 5,
    mineral: Gem.FireOpal,
    colors: [Color.Red, Color.YellowLight, Color.Black],
    tarrot: TarrotMajor.Rebirth,
    name: "snake",
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Topaz,
    colors: [Color.Blue, Color.White, Color.Brown],
    tarrot: TarrotMajor.TheStar,
    name: "hardworker",
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 8,
    mineral: Gem.Onyx,
    colors: [Color.Black, Color.Blue, Color.BlueDeep],
    tarrot: TarrotMajor.Judgment,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 5,
    mineral: Gem.Amber,
    colors: [Color.White, Color.RedDeep, Color.BlueDeep],
    tarrot: TarrotMajor.TheSun,
    name: "eagle",
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Rhodolite,
    colors: [Color.Purple, Color.RedDeep, Color.Cyan],
    tarrot: TarrotMajor.Rebirth,
    name: "scorpio",
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.BlackPearl,
    colors: [Color.White, Color.BlueLight, Color.Grey],
    tarrot: TarrotMajor.TheHighPriestess,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Topaz,
    colors: [Color.Blue, Color.Brown, Color.OrangeDeep],
    tarrot: TarrotMajor.TheChariot,
    name: "rooster",
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 8,
    mineral: Gem.Diamond,
    colors: [Color.Black, Color.OrangeDeep, Color.BlueDeep],
    tarrot: TarrotMajor.Lust,
    name: "gorilla",
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.RedTourmaline,
    colors: [Color.RedLight, Color.Green, Color.OrangeLight],
    tarrot: TarrotMajor.TheStar,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Ruby,
    colors: [Color.RedDeep, Color.Brown, Color.Grey],
    tarrot: TarrotMajor.Temperance,
    name: "magic_goat",
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.BlueTourmaline,
    colors: [Color.YellowLight, Color.RedLight, Color.Purple],
    tarrot: TarrotMajor.TheMagician,
    name: "artist",
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Chrysolite,
    colors: [Color.BlueDeep, Color.Purple, Color.RedDeep],
    tarrot: TarrotMajor.TheHierophant,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 7,
    mineral: Gem.Pearl,
    colors: [Color.Black, Color.Grey, Color.Lime],
    tarrot: TarrotMajor.TheHangedMan,
    name: "raven",
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Emerald,
    colors: [Color.Blue, Color.White, Color.OrangeLight],
    tarrot: TarrotMajor.TheChariot,
    name: "sailing_ship",
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 7,
    mineral: Gem.RedTourmaline,
    colors: [Color.Pink, Color.PinkDeep, Color.PurpleLight],
    tarrot: TarrotMajor.TheMagician,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 5,
    mineral: Gem.BlackPearl,
    colors: [Color.PurpleDeep, Color.RedDeep, Color.Black],
    tarrot: TarrotMajor.Judgment,
    name: "wolf",
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 5,
    mineral: Gem.Ruby,
    colors: [Color.PurpleDeep, Color.Yellow, Color.Blue],
    tarrot: TarrotMajor.TheChariot,
    name: "man_throw_spear",
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 9,
    mineral: Gem.OrangeSapphire,
    colors: [Color.YellowLight, Color.PurpleLight, Color.Yellow],
    tarrot: TarrotMajor.Rebirth,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 5,
    mineral: Gem.Opal,
    colors: [Color.Cyan, Color.Yellow, Color.Blue],
    tarrot: TarrotMajor.Rebirth,
    name: "blue_phoenix",
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.OrangeSapphire,
    colors: [Color.OrangeDeep, Color.White, Color.Black],
    tarrot: TarrotMajor.Strength,
    name: "tiger",
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Opal,
    colors: [Color.Black, Color.PinkLight, Color.Lime],
    tarrot: TarrotMajor.TheChariot,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 6,
    mineral: Gem.Zircon,
    colors: [Color.BlueLight, Color.Blue, Color.OrangeLight],
    tarrot: TarrotMajor.TheHierophant,
    name: "xiezhi",
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 8,
    mineral: Gem.Alexandrite,
    colors: [Color.White, Color.OrangeLight, Color.Black],
    tarrot: TarrotMajor.Justice,
    name: "swam",
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.low,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Zircon,
    colors: [Color.BlueGrey, Color.White, Color.GreenLight],
    tarrot: TarrotMajor.TheSun,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 5,
    mineral: Gem.Amethyst,
    colors: [Color.PinkLight, Color.Pink, Color.PinkDeep],
    tarrot: TarrotMajor.Lust,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.BlueSapphire,
    colors: [Color.BlueDeep, Color.Purple, Color.BlueGrey],
    tarrot: TarrotMajor.TheHighPriestess,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 8,
    mineral: Gem.Ruby,
    colors: [Color.RedDeep, Color.White, Color.BlueDeep],
    tarrot: TarrotMajor.Justice,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Amethyst,
    colors: [Color.Lime, Color.YellowLight, Color.Brown],
    tarrot: TarrotMajor.TheHangedMan,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.BlackPearl,
    colors: [Color.Lime, Color.Grey, Color.White],
    tarrot: TarrotMajor.TheEmperor,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 7,
    mineral: Gem.Rhodolite,
    colors: [Color.PurpleLight, Color.Purple, Color.PurpleDeep],
    tarrot: TarrotMajor.TheChariot,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Emerald,
    colors: [Color.BlueLight, Color.Lime, Color.GreenLight],
    tarrot: TarrotMajor.TheWorld,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Onyx,
    colors: [Color.Black, Color.OrangeDeep, Color.Brown],
    tarrot: TarrotMajor.Judgment,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 6,
    mineral: Gem.BlueSapphire,
    colors: [Color.BlueLight, Color.Green, Color.PinkDeep],
    tarrot: TarrotMajor.TheEmpress,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.BlackPearl,
    colors: [Color.Red, Color.OrangeDeep, Color.PurpleDeep],
    tarrot: TarrotMajor.TheTower,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 8,
    mineral: Gem.Opal,
    colors: [Color.RedLight, Color.YellowLight, Color.GreenLight],
    tarrot: TarrotMajor.TheHierophant,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 9,
    mineral: Gem.Amethyst,
    colors: [Color.BlueDeep, Color.Grey, Color.Brown],
    tarrot: TarrotMajor.TheHermit,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Pearl,
    colors: [Color.Grey, Color.GreenDeep, Color.White],
    tarrot: TarrotMajor.TheEmpress,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Kyanite,
    colors: [Color.BlueLight, Color.White, Color.BlueGrey],
    tarrot: TarrotMajor.Justice,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.OrangeTopaz,
    colors: [Color.Orange, Color.Yellow, Color.RedLight],
    tarrot: TarrotMajor.Temperance,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.BlueTourmaline,
    colors: [Color.BlueLight, Color.Blue, Color.BlueDeep],
    tarrot: TarrotMajor.TheHermit,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 5,
    mineral: Gem.BlackTopaz,
    colors: [Color.Black, Color.Lime, Color.YellowLight],
    tarrot: TarrotMajor.TheMagician,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 8,
    mineral: Gem.Ruby,
    colors: [Color.RedDeep, Color.White, Color.Red],
    tarrot: TarrotMajor.TheHierophant,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Carbuncle,
    colors: [Color.Purple, Color.Blue, Color.Pink],
    tarrot: TarrotMajor.TheChariot,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.OrangeTopaz,
    colors: [Color.Yellow, Color.Orange, Color.BlueLight],
    tarrot: TarrotMajor.TheSun,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 6,
    mineral: Gem.FireOpal,
    colors: [Color.RedLight, Color.YellowLight, Color.OrangeLight],
    tarrot: TarrotMajor.TheFool,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Carbuncle,
    colors: [Color.White, Color.RedLight, Color.GreenDeep],
    tarrot: TarrotMajor.Temperance,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Aquamarine,
    colors: [Color.PurpleLight, Color.BlueLight, Color.PinkLight],
    tarrot: TarrotMajor.TheFool,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Onyx,
    colors: [Color.RedDeep, Color.GreenDeep, Color.Black],
    tarrot: TarrotMajor.TheChariot,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 5,
    mineral: Gem.Amber,
    colors: [Color.White, Color.PinkLight, Color.Yellow],
    tarrot: TarrotMajor.TheStar,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Alexandrite,
    colors: [Color.Yellow, Color.Lime, Color.Green],
    tarrot: TarrotMajor.TheEmpress,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 8,
    mineral: Gem.Amber,
    colors: [Color.BlueLight, Color.Orange, Color.White],
    tarrot: TarrotMajor.TheWheelOfFortune,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 9,
    mineral: Gem.Amethyst,
    colors: [Color.White, Color.BlueDeep, Color.White],
    tarrot: TarrotMajor.TheHermit,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Rhodolite,
    colors: [Color.PurpleLight, Color.BlueLight, Color.White],
    tarrot: TarrotMajor.Temperance,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Aquamarine,
    colors: [Color.GreenLight, Color.Green, Color.GreenDeep],
    tarrot: TarrotMajor.Strength,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 7,
    mineral: Gem.BlackTopaz,
    colors: [Color.Grey, Color.Lime, Color.BlueDeep],
    tarrot: TarrotMajor.TheHermit,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.FireOpal,
    colors: [Color.White, Color.OrangeDeep, Color.Black],
    tarrot: TarrotMajor.Strength,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 8,
    mineral: Gem.Citrine,
    colors: [Color.Brown, Color.Grey, Color.Blue],
    tarrot: TarrotMajor.TheTower,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 5,
    mineral: Gem.RedTourmaline,
    colors: [Color.Red, Color.RedDeep, Color.White],
    tarrot: TarrotMajor.Temperance,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Topaz,
    colors: [Color.BlueDeep, Color.BlueGrey, Color.Blue],
    tarrot: TarrotMajor.TheMoon,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 7,
    mineral: Gem.BlackTopaz,
    colors: [Color.Black, Color.Red, Color.BlueDeep],
    tarrot: TarrotMajor.TheHierophant,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 5,
    mineral: Gem.Ruby,
    colors: [Color.Purple, Color.Pink, Color.Yellow],
    tarrot: TarrotMajor.TheFool,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.OrangeTopaz,
    colors: [Color.BlueGrey, Color.Brown, Color.RedDeep],
    tarrot: TarrotMajor.TheChariot,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 5,
    mineral: Gem.Alexandrite,
    colors: [Color.PinkDeep, Color.Pink, Color.PinkLight],
    tarrot: TarrotMajor.Strength,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Chrysolite,
    colors: [Color.Black, Color.Yellow, Color.Lime],
    tarrot: TarrotMajor.TheWorld,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 7,
    mineral: Gem.FireOpal,
    colors: [Color.BlueDeep, Color.OrangeLight, Color.White],
    tarrot: TarrotMajor.TheSun,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 5,
    mineral: Gem.Ruby,
    colors: [Color.OrangeDeep, Color.White, Color.BlueDeep],
    tarrot: TarrotMajor.Strength,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 6,
    mineral: Gem.RedSpinel,
    colors: [Color.Cyan, Color.Brown, Color.RedLight],
    tarrot: TarrotMajor.TheLovers,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 5,
    mineral: Gem.Carbuncle,
    colors: [Color.PinkLight, Color.Pink, Color.PurpleDeep],
    tarrot: TarrotMajor.TheFool,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 8,
    mineral: Gem.Alexandrite,
    colors: [Color.Grey, Color.Blue, Color.White],
    tarrot: TarrotMajor.TheChariot,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 7,
    mineral: Gem.OrangeSapphire,
    colors: [Color.BlueDeep, Color.Brown, Color.RedDeep],
    tarrot: TarrotMajor.Judgment,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.PurpleSpinel,
    colors: [Color.Cyan, Color.Pink, Color.Yellow],
    tarrot: TarrotMajor.TheFool,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 5,
    mineral: Gem.Diamond,
    colors: [Color.Red, Color.White, Color.Grey],
    tarrot: TarrotMajor.TheStar,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 7,
    mineral: Gem.OrangeSapphire,
    colors: [Color.Green, Color.PurpleDeep, Color.Orange],
    tarrot: TarrotMajor.TheHierophant,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.OrangeSapphire,
    colors: [Color.White, Color.OrangeLight, Color.Orange],
    tarrot: TarrotMajor.TheFool,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Emerald,
    colors: [Color.Green, Color.OrangeDeep, Color.PurpleDeep],
    tarrot: TarrotMajor.Strength,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Citrine,
    colors: [Color.Yellow, Color.White, Color.Black],
    tarrot: TarrotMajor.TheEmpress,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 5,
    mineral: Gem.Garnet,
    colors: [Color.Brown, Color.BlueDeep, Color.RedDeep],
    tarrot: TarrotMajor.TheWheelOfFortune,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Ruby,
    colors: [Color.RedDeep, Color.RedLight, Color.Grey],
    tarrot: TarrotMajor.Strength,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 5,
    mineral: Gem.FireOpal,
    colors: [Color.Orange, Color.Yellow, Color.Red],
    tarrot: TarrotMajor.Strength,
    name: "phoenix",
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.BlueTourmaline,
    colors: [Color.White, Color.BlueLight, Color.Purple],
    tarrot: TarrotMajor.TheHighPriestess,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.OrangeSapphire,
    colors: [Color.Grey, Color.Teal, Color.Brown],
    tarrot: TarrotMajor.TheMagician,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 8,
    mineral: Gem.Amber,
    colors: [Color.OrangeLight, Color.PinkLight, Color.Red],
    tarrot: TarrotMajor.Lust,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Kyanite,
    colors: [Color.Grey, Color.Brown, Color.PurpleLight],
    tarrot: TarrotMajor.TheHermit,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 7,
    mineral: Gem.OrangeSapphire,
    colors: [Color.White, Color.Yellow, Color.YellowLight],
    tarrot: TarrotMajor.TheWorld,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 6,
    mineral: Gem.RedSpinel,
    colors: [Color.Orange, Color.Brown, Color.Yellow],
    tarrot: TarrotMajor.TheHierophant,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Amethyst,
    colors: [Color.OrangeDeep, Color.Cyan, Color.Black],
    tarrot: TarrotMajor.Justice,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.YellowSapphire,
    colors: [Color.Brown, Color.YellowLight, Color.White],
    tarrot: TarrotMajor.TheChariot,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Onyx,
    colors: [Color.PurpleDeep, Color.Brown, Color.Green],
    tarrot: TarrotMajor.TheEmperor,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 8,
    mineral: Gem.OrangeSapphire,
    colors: [Color.Lime, Color.Brown, Color.GreenLight],
    tarrot: TarrotMajor.Temperance,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.RedTourmaline,
    colors: [Color.PinkDeep, Color.BlueDeep, Color.Purple],
    tarrot: TarrotMajor.TheFool,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Rhodolite,
    colors: [Color.PurpleLight, Color.White, Color.OrangeLight],
    tarrot: TarrotMajor.TheWheelOfFortune,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Alexandrite,
    colors: [Color.Blue, Color.BlueDeep, Color.RedDeep],
    tarrot: TarrotMajor.TheWorld,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.PurpleSpinel,
    colors: [Color.PurpleDeep, Color.White, Color.Pink],
    tarrot: TarrotMajor.Justice,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.FireOpal,
    colors: [Color.Orange, Color.RedLight, Color.Cyan],
    tarrot: TarrotMajor.Strength,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.BlueSapphire,
    colors: [Color.White, Color.Purple, Color.Yellow],
    tarrot: TarrotMajor.TheHighPriestess,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 6,
    mineral: Gem.PurpleSpinel,
    colors: [Color.BlueLight, Color.Blue, Color.PurpleLight],
    tarrot: TarrotMajor.TheMoon,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 8,
    mineral: Gem.RedTourmaline,
    colors: [Color.Orange, Color.Yellow, Color.Grey],
    tarrot: TarrotMajor.TheSun,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 8,
    mineral: Gem.FireOpal,
    colors: [Color.Blue, Color.Black, Color.Red],
    tarrot: TarrotMajor.TheWheelOfFortune,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Zircon,
    colors: [Color.Lime, Color.GreenLight, Color.Yellow],
    tarrot: TarrotMajor.TheLovers,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.OrangeSapphire,
    colors: [Color.Orange, Color.PurpleLight, Color.BlueLight],
    tarrot: TarrotMajor.TheSun,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Rhodolite,
    colors: [Color.White, Color.BlueLight, Color.Black],
    tarrot: TarrotMajor.TheHighPriestess,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Diamond,
    colors: [Color.RedDeep, Color.PurpleDeep, Color.BlueDeep],
    tarrot: TarrotMajor.TheEmperor,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 6,
    mineral: Gem.Rhodolite,
    colors: [Color.Purple, Color.PurpleLight, Color.YellowLight],
    tarrot: TarrotMajor.TheEmpress,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 9,
    mineral: Gem.RedTourmaline,
    colors: [Color.Red, Color.Grey, Color.RedLight],
    tarrot: TarrotMajor.Temperance,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.ordinary,
  ): SymbolCombination(
    digit: 5,
    mineral: Gem.Opal,
    colors: [Color.Cyan, Color.OrangeLight, Color.RedLight],
    tarrot: TarrotMajor.TheChariot,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.BlueTourmaline,
    colors: [Color.BlueGrey, Color.RedLight, Color.Grey],
    tarrot: TarrotMajor.TheHangedMan,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 7,
    mineral: Gem.BlackPearl,
    colors: [Color.Black, Color.BlueLight, Color.White],
    tarrot: TarrotMajor.TheMoon,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 9,
    mineral: Gem.Alexandrite,
    colors: [Color.Green, Color.Purple, Color.Yellow],
    tarrot: TarrotMajor.Rebirth,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 9,
    mineral: Gem.Diamond,
    colors: [Color.Yellow, Color.Orange, Color.BlueGrey],
    tarrot: TarrotMajor.Justice,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Chrysolite,
    colors: [Color.Grey, Color.Brown, Color.BlueGrey],
    tarrot: TarrotMajor.TheHermit,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 5,
    mineral: Gem.PurpleSpinel,
    colors: [Color.PurpleLight, Color.RedLight, Color.Cyan],
    tarrot: TarrotMajor.TheMagician,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Kyanite,
    colors: [Color.Pink, Color.Cyan, Color.Yellow],
    tarrot: TarrotMajor.TheLovers,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Ruby,
    colors: [Color.Red, Color.White, Color.Brown],
    tarrot: TarrotMajor.TheTower,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 8,
    mineral: Gem.RedTourmaline,
    colors: [Color.BlueDeep, Color.OrangeLight, Color.White],
    tarrot: TarrotMajor.Strength,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Rhodolite,
    colors: [Color.YellowLight, Color.PurpleLight, Color.Purple],
    tarrot: TarrotMajor.TheEmpress,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Aquamarine,
    colors: [Color.BlueGrey, Color.BlueDeep, Color.White],
    tarrot: TarrotMajor.TheMoon,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.BlackTopaz,
    colors: [Color.Black, Color.GreenDeep, Color.RedLight],
    tarrot: TarrotMajor.Justice,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 6,
    mineral: Gem.Chrysolite,
    colors: [Color.Lime, Color.Teal, Color.YellowLight],
    tarrot: TarrotMajor.Judgment,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 9,
    mineral: Gem.Zircon,
    colors: [Color.Grey, Color.Brown, Color.White],
    tarrot: TarrotMajor.TheHermit,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Onyx,
    colors: [Color.PinkLight, Color.Pink, Color.PinkDeep],
    tarrot: TarrotMajor.TheMagician,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Emerald,
    colors: [Color.Green, Color.Yellow, Color.Lime],
    tarrot: TarrotMajor.TheEmperor,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Kyanite,
    colors: [Color.BlueLight, Color.White, Color.OrangeLight],
    tarrot: TarrotMajor.Temperance,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Aquamarine,
    colors: [Color.White, Color.BlueLight, Color.Grey],
    tarrot: TarrotMajor.TheMoon,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Alexandrite,
    colors: [Color.RedDeep, Color.BlueGrey, Color.RedLight],
    tarrot: TarrotMajor.TheChariot,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Amethyst,
    colors: [Color.OrangeLight, Color.GreenDeep, Color.Lime],
    tarrot: TarrotMajor.TheEmpress,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Opal,
    colors: [Color.Lime, Color.RedLight, Color.BlueLight],
    tarrot: TarrotMajor.TheMagician,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 9,
    mineral: Gem.Topaz,
    colors: [Color.Grey, Color.PurpleLight, Color.PinkLight],
    tarrot: TarrotMajor.Temperance,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.YellowSapphire,
    colors: [Color.Yellow, Color.Blue, Color.YellowLight],
    tarrot: TarrotMajor.TheSun,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 6,
    mineral: Gem.BlueTourmaline,
    colors: [Color.Pink, Color.RedLight, Color.Yellow],
    tarrot: TarrotMajor.TheLovers,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Peridot,
    colors: [Color.Brown, Color.BlueLight, Color.Green],
    tarrot: TarrotMajor.Judgment,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 7,
    mineral: Gem.Topaz,
    colors: [Color.Cyan, Color.YellowLight, Color.White],
    tarrot: TarrotMajor.TheStar,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.low,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 5,
    mineral: Gem.BlueSapphire,
    colors: [Color.OrangeLight, Color.RedLight, Color.PurpleDeep],
    tarrot: TarrotMajor.TheChariot,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 6,
    mineral: Gem.Onyx,
    colors: [Color.GreenLight, Color.Pink, Color.Red],
    tarrot: TarrotMajor.TheEmpress,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 5,
    mineral: Gem.PurpleSpinel,
    colors: [Color.PinkLight, Color.BlueGrey, Color.RedDeep],
    tarrot: TarrotMajor.Strength,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Onyx,
    colors: [Color.Red, Color.Blue, Color.Orange],
    tarrot: TarrotMajor.TheTower,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 8,
    mineral: Gem.Ruby,
    colors: [Color.PinkDeep, Color.RedDeep, Color.Yellow],
    tarrot: TarrotMajor.TheEmperor,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Citrine,
    colors: [Color.OrangeLight, Color.Red, Color.Black],
    tarrot: TarrotMajor.TheEmpress,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Peridot,
    colors: [Color.Teal, Color.Lime, Color.Green],
    tarrot: TarrotMajor.Judgment,
    name: "pike_fish",
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 8,
    mineral: Gem.Amethyst,
    colors: [Color.Pink, Color.Purple, Color.Yellow],
    tarrot: TarrotMajor.TheHangedMan,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 9,
    mineral: Gem.BlackTopaz,
    colors: [Color.Black, Color.GreenDeep, Color.Brown],
    tarrot: TarrotMajor.TheMagician,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 9,
    mineral: Gem.Citrine,
    colors: [Color.GreenLight, Color.Yellow, Color.BlueLight],
    tarrot: TarrotMajor.TheMagician,
    name: "mage",
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 5,
    mineral: Gem.OrangeSapphire,
    colors: [Color.White, Color.PinkDeep, Color.Yellow],
    tarrot: TarrotMajor.Justice,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 7,
    mineral: Gem.BlueSapphire,
    colors: [Color.Blue, Color.White, Color.RedDeep],
    tarrot: TarrotMajor.TheHierophant,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Beryl,
    colors: [Color.Cyan, Color.White, Color.OrangeLight],
    tarrot: TarrotMajor.TheStar,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Carbuncle,
    colors: [Color.PinkLight, Color.Cyan, Color.Brown],
    tarrot: TarrotMajor.Lust,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 6,
    mineral: Gem.Garnet,
    colors: [Color.Orange, Color.White, Color.Yellow],
    tarrot: TarrotMajor.TheStar,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.OrangeTopaz,
    colors: [Color.Yellow, Color.Orange, Color.OrangeDeep],
    tarrot: TarrotMajor.TheHierophant,
    name: "golden_bull",
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 5,
    mineral: Gem.Emerald,
    colors: [Color.Brown, Color.OrangeLight, Color.Green],
    tarrot: TarrotMajor.TheChariot,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Kyanite,
    colors: [Color.BlueLight, Color.Blue, Color.BlueDeep],
    tarrot: TarrotMajor.Strength,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 6,
    mineral: Gem.Kyanite,
    colors: [Color.Grey, Color.BlueGrey, Color.White],
    tarrot: TarrotMajor.TheWorld,
    name: "elephant",
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Chrysolite,
    colors: [Color.GreenDeep, Color.Green, Color.GreenLight],
    tarrot: TarrotMajor.Justice,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.RedSpinel,
    colors: [Color.BlueLight, Color.Red, Color.Orange],
    tarrot: TarrotMajor.TheTower,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 8,
    mineral: Gem.Kyanite,
    colors: [Color.RedDeep, Color.Red, Color.RedLight],
    tarrot: TarrotMajor.TheEmperor,
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.Beryl,
    colors: [Color.BlueGrey, Color.BlueLight, Color.Grey],
    tarrot: TarrotMajor.TheHighPriestess,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Zircon,
    colors: [Color.Brown, Color.Green, Color.Pink],
    tarrot: TarrotMajor.TheLovers,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 8,
    mineral: Gem.Rhodolite,
    colors: [Color.PurpleDeep, Color.Brown, Color.Green],
    tarrot: TarrotMajor.Strength,
    name: "bear",
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 5,
    mineral: Gem.Peridot,
    colors: [Color.Yellow, Color.Lime, Color.Red],
    tarrot: TarrotMajor.TheMagician,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.BlackPearl,
    colors: [Color.BlueGrey, Color.Red, Color.Black],
    tarrot: TarrotMajor.Justice,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.ordinary,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.OrangeSapphire,
    colors: [Color.Brown, Color.YellowLight, Color.White],
    tarrot: TarrotMajor.TheEmpress,
    name: "griffin",
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Kyanite,
    colors: [Color.Grey, Color.Yellow, Color.PurpleLight],
    tarrot: TarrotMajor.TheHangedMan,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Peridot,
    colors: [Color.GreenDeep, Color.Black, Color.BlueDeep],
    tarrot: TarrotMajor.Rebirth,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Aquamarine,
    colors: [Color.BlueDeep, Color.Grey, Color.Blue],
    tarrot: TarrotMajor.TheFool,
    name: "shark",
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Beryl,
    colors: [Color.Cyan, Color.Orange, Color.Red],
    tarrot: TarrotMajor.TheSun,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 5,
    mineral: Gem.OrangeSapphire,
    colors: [Color.White, Color.BlueLight, Color.Yellow],
    tarrot: TarrotMajor.TheChariot,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Emerald,
    colors: [Color.GreenDeep, Color.Yellow, Color.Teal],
    tarrot: TarrotMajor.TheHangedMan,
    name: "gremlin",
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Diamond,
    colors: [Color.BlueLight, Color.Red, Color.Brown],
    tarrot: TarrotMajor.Strength,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 3,
    mineral: Gem.Garnet,
    colors: [Color.Pink, Color.YellowLight, Color.PinkLight],
    tarrot: TarrotMajor.Temperance,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.low,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 8,
    mineral: Gem.Carbuncle,
    colors: [Color.RedDeep, Color.Teal, Color.Red],
    tarrot: TarrotMajor.Rebirth,
    name: "manticore",
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 2,
    mineral: Gem.BlueTourmaline,
    colors: [Color.Pink, Color.OrangeLight, Color.Red],
    tarrot: TarrotMajor.TheLovers,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Amethyst,
    colors: [Color.PurpleLight, Color.YellowLight, Color.Red],
    tarrot: TarrotMajor.TheChariot,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 6,
    mineral: Gem.Amber,
    colors: [Color.Brown, Color.Teal, Color.Grey],
    tarrot: TarrotMajor.TheTower,
    name: "golem",
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.Emerald,
    colors: [Color.PurpleDeep, Color.Yellow, Color.GreenLight],
    tarrot: TarrotMajor.TheEmperor,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 6,
    mineral: Gem.FireOpal,
    colors: [Color.Orange, Color.Brown, Color.Lime],
    tarrot: TarrotMajor.TheWheelOfFortune,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Onyx,
    colors: [Color.OrangeDeep, Color.Cyan, Color.Black],
    tarrot: TarrotMajor.TheWheelOfFortune,
    name: "magic_elk",
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 7,
    mineral: Gem.Rhodolite,
    colors: [Color.RedDeep, Color.BlueLight, Color.White],
    tarrot: TarrotMajor.TheStar,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.FireOpal,
    colors: [Color.White, Color.OrangeDeep, Color.Black],
    tarrot: TarrotMajor.Strength,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.ordinary,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 8,
    mineral: Gem.Amber,
    colors: [Color.Orange, Color.Brown, Color.Yellow],
    tarrot: TarrotMajor.Justice,
    name: "winged_wolf",
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 9,
    mineral: Gem.Chrysolite,
    colors: [Color.Teal, Color.BlueDeep, Color.GreenDeep],
    tarrot: TarrotMajor.Justice,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 5,
    mineral: Gem.PurpleSpinel,
    colors: [Color.Yellow, Color.Pink, Color.Red],
    tarrot: TarrotMajor.TheFool,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.low,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.BlueTourmaline,
    colors: [Color.White, Color.PinkLight, Color.BlueLight],
    tarrot: TarrotMajor.TheLovers,
    name: "snowman",
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Amber,
    colors: [Color.Brown, Color.Blue, Color.BlueGrey],
    tarrot: TarrotMajor.TheHierophant,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 4,
    mineral: Gem.RedSpinel,
    colors: [Color.Grey, Color.BlueDeep, Color.RedDeep],
    tarrot: TarrotMajor.TheWorld,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.ordinary,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 1,
    mineral: Gem.Ruby,
    colors: [Color.Red, Color.Yellow, Color.Orange],
    tarrot: TarrotMajor.Strength,
    name: "red_dragon",
  ),
  PropheciesRange(
    mood: Range.low,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 6,
    mineral: Gem.BlueSapphire,
    colors: [Color.Blue, Color.Grey, Color.PurpleLight],
    tarrot: TarrotMajor.TheMoon,
  ),
  PropheciesRange(
    mood: Range.ordinary,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 5,
    mineral: Gem.Carbuncle,
    colors: [Color.Pink, Color.Red, Color.RedLight],
    tarrot: TarrotMajor.TheFool,
  ),
  PropheciesRange(
    mood: Range.high,
    intuition: Range.high,
    luck: Range.high,
    ambition: Range.high,
    internalStrength: Range.high,
  ): SymbolCombination(
    digit: 7,
    mineral: Gem.Alexandrite,
    colors: [Color.Green, Color.Grey, Color.BlueGrey],
    tarrot: TarrotMajor.TheWorld,
    name: "tree_of_wisdom",
  ),
};

/// returns PreparedSymbolCombination from prophecies object
PreparedSymbolCombination getSymbolCombination(
    Map<ProphecyType, ProphecyEntity> prophecy) {
  //

  final prophecyValues = PropheciesRange(
    mood: rangeFromValue(prophecy[ProphecyType.ROOT].value),
    intuition: rangeFromValue(prophecy[ProphecyType.THROAT].value),
    luck: rangeFromValue(prophecy[ProphecyType.SACRAL].value),
    ambition: rangeFromValue(prophecy[ProphecyType.SOLAR].value),
    internalStrength: rangeFromValue(prophecy[ProphecyType.HEART].value),
  );

  return PreparedSymbolCombination(SymbolCombinations[prophecyValues]);
}

@immutable
class SymbolCombination {
  final int digit;
  final Gem mineral;
  final List<Color> colors;
  final TarrotMajor tarrot;
  final String name;

  const SymbolCombination({
    @required this.digit,
    @required this.mineral,
    @required this.colors,
    @required this.tarrot,
    this.name = "",
  });
}

@immutable
class PreparedSymbolCombination {
  final String digit;
  final String mineral;
  final List<int> colors;
  final String tarrot;

  PreparedSymbolCombination(SymbolCombination sv)
      : this.digit = DigitToFileName[sv.digit],
        this.mineral = GemToFileName[sv.mineral],
        this.colors = [
          ColorToInt[sv.colors[0]],
          ColorToInt[sv.colors[1]],
          ColorToInt[sv.colors[2]],
        ],
        this.tarrot = TarrotMajorToFileName[sv.tarrot];
}
